// docs/snippets/document-field/generated/phone/phone-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidPhone } from "@brazilian-utils/brazilian-utils";
import { PhoneField } from "./phone-field";

export function PhoneForm() {
  const { control, handleSubmit } = useForm({
    defaultValues: { phone: "" },
    mode: "onTouched",
  });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="phone"
        control={control}
        rules={{
          required: "Enter a Phone",
          validate: (value) => isValidPhone(value) || "Enter a valid Phone",
        }}
        render={({ field, fieldState }) => (
          <>
            <PhoneField
              {...field}
              aria-invalid={fieldState.invalid}
              aria-describedby="phone-error"
            />
            {/* On the page from the start, and announced when it gets its text: nothing moves
                focus to the field, so the message has to speak for itself. */}
            <p id="phone-error" role="alert">
              {fieldState.error?.message}
            </p>
          </>
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}

// docs/snippets/document-field/generated/phone/phone-form.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { isValidPhone } from "@brazilian-utils/brazilian-utils";
import PhoneField from "./phone-field.vue";

const { defineField, errors, handleSubmit } = useForm({
  initialValues: { phone: "" },
  validationSchema: {
    phone: (value: string) => isValidPhone(value) || "Enter a valid Phone",
  },
});

// The attributes carry the blur handler, so the field is validated once it is left.
const [phone, phoneAttrs] = defineField("phone", {
  validateOnModelUpdate: false,
});

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <PhoneField
      v-model="phone"
      v-bind="phoneAttrs"
      :aria-invalid="Boolean(errors.phone)"
      aria-describedby="phone-error"
    />
    <!-- On the page from the start, and announced when it gets its text: nothing moves focus
         to the field here, so the message has to speak for itself. -->
    <p id="phone-error" role="alert">{{ errors.phone }}</p>
    <button type="submit">Submit</button>
  </form>
</template>
