// docs/snippets/address-form/react/address-form.tsx
import { useId, useState } from "react";
import {
  formatCep,
  getAddressInfoByCep,
  isValidCep,
} from "@brazilian-utils/brazilian-utils";

const EMPTY = { street: "", neighborhood: "", city: "", state: "" };

export function AddressForm() {
  const id = useId();
  const [cep, setCep] = useState("");
  const [address, setAddress] = useState(EMPTY);
  const [status, setStatus] = useState("");

  async function onCepChange(typed: string) {
    const masked = formatCep(typed);

    setCep(masked);

    // The lookup is worth a request only once the CEP is complete.
    if (!isValidCep(masked)) return setStatus("");

    setStatus("Looking up…");

    try {
      const found = await getAddressInfoByCep(masked);

      setAddress(found);
      setStatus("");
    } catch {
      setAddress(EMPTY);
      setStatus("No address for this CEP");
    }
  }

  return (
    <form onSubmit={(event) => event.preventDefault()}>
      <label htmlFor={id}>CEP</label>
      <input
        id={id}
        inputMode="numeric"
        autoComplete="postal-code"
        placeholder="00000-000"
        value={cep}
        aria-describedby={`${id}-status`}
        onChange={(event) => onCepChange(event.currentTarget.value)}
      />
      {/* On the page from the start, and announced when it gets its text. */}
      <output id={`${id}-status`}>{status}</output>

      <label htmlFor={`${id}-street`}>Street</label>
      <input
        id={`${id}-street`}
        autoComplete="address-line1"
        value={address.street}
        onChange={(event) =>
          setAddress({ ...address, street: event.currentTarget.value })
        }
      />

      <label htmlFor={`${id}-neighborhood`}>Neighborhood</label>
      <input
        id={`${id}-neighborhood`}
        value={address.neighborhood}
        onChange={(event) =>
          setAddress({ ...address, neighborhood: event.currentTarget.value })
        }
      />

      <label htmlFor={`${id}-city`}>City</label>
      <input
        id={`${id}-city`}
        autoComplete="address-level2"
        value={address.city}
        onChange={(event) => setAddress({ ...address, city: event.currentTarget.value })}
      />

      <label htmlFor={`${id}-state`}>State</label>
      <input
        id={`${id}-state`}
        autoComplete="address-level1"
        maxLength={2}
        value={address.state}
        onChange={(event) => setAddress({ ...address, state: event.currentTarget.value })}
      />
    </form>
  );
}

// docs/snippets/address-form/vue/address-form.vue
<script setup lang="ts">
import { reactive, ref, useId } from "vue";
import {
  formatCep,
  getAddressInfoByCep,
  isValidCep,
} from "@brazilian-utils/brazilian-utils";

const EMPTY = { street: "", neighborhood: "", city: "", state: "" };

const id = useId();
const cep = ref("");
const status = ref("");
const address = reactive({ ...EMPTY });

async function onCepChange(event: Event) {
  cep.value = formatCep((event.target as HTMLInputElement).value);

  // The lookup is worth a request only once the CEP is complete.
  if (!isValidCep(cep.value)) {
    status.value = "";
    return;
  }

  status.value = "Looking up…";

  try {
    Object.assign(address, await getAddressInfoByCep(cep.value));
    status.value = "";
  } catch {
    Object.assign(address, EMPTY);
    status.value = "No address for this CEP";
  }
}
</script>

<template>
  <form @submit.prevent>
    <label :for="id">CEP</label>
    <input
      :id="id"
      inputmode="numeric"
      autocomplete="postal-code"
      placeholder="00000-000"
      :value="cep"
      :aria-describedby="`${id}-status`"
      @input="onCepChange"
    />
    <!-- On the page from the start, and announced when it gets its text. -->
    <output :id="`${id}-status`">{{ status }}</output>

    <label :for="`${id}-street`">Street</label>
    <input :id="`${id}-street`" v-model="address.street" autocomplete="address-line1" />

    <label :for="`${id}-neighborhood`">Neighborhood</label>
    <input :id="`${id}-neighborhood`" v-model="address.neighborhood" />

    <label :for="`${id}-city`">City</label>
    <input :id="`${id}-city`" v-model="address.city" autocomplete="address-level2" />

    <label :for="`${id}-state`">State</label>
    <input
      :id="`${id}-state`"
      v-model="address.state"
      autocomplete="address-level1"
      maxlength="2"
    />
  </form>
</template>
