// docs/snippets/usage/signup-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidCpf } from "@brazilian-utils/brazilian-utils";
import { CpfField } from "./cpf-field";

type SignupValues = {
  cpf: string;
};

export function SignupForm() {
  const { control, handleSubmit } = useForm<SignupValues>({
    defaultValues: { cpf: "" },
  });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="cpf"
        control={control}
        rules={{ validate: (cpf) => isValidCpf(cpf) || "Enter a valid CPF" }}
        render={({ field, fieldState }) => (
          <>
            <CpfField {...field} />
            {fieldState.error && <p role="alert">{fieldState.error.message}</p>}
          </>
        )}
      />
      <button type="submit">Sign up</button>
    </form>
  );
}

// docs/snippets/usage/signup-form.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { isValidCpf } from "@brazilian-utils/brazilian-utils";
import CpfField from "./cpf-field.vue";

const { defineField, errors, handleSubmit } = useForm({
  initialValues: { cpf: "" },
  validationSchema: {
    cpf: (cpf: string) => isValidCpf(cpf) || "Enter a valid CPF",
  },
});

const [cpf] = defineField("cpf");

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <CpfField v-model="cpf" />
    <p v-if="errors.cpf" role="alert">{{ errors.cpf }}</p>
    <button type="submit">Sign up</button>
  </form>
</template>
