// docs/snippets/document-field/generated/cpf/vue/cpf-form.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { isValidCpf } from "@brazilian-utils/brazilian-utils";
import CpfField from "./cpf-field.vue";

const { defineField, errors, handleSubmit } = useForm({
  initialValues: { cpf: "" },
  validationSchema: {
    cpf: (value: string) => isValidCpf(value) || "Enter a valid CPF",
  },
});

// The attributes carry the blur handler, so the field is validated once it is left.
const [cpf, cpfAttrs] = defineField("cpf", {
  validateOnModelUpdate: false,
});

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <CpfField
      v-model="cpf"
      v-bind="cpfAttrs"
      :error-message="errors.cpf"
    />
    <button type="submit">Submit</button>
  </form>
</template>

// docs/snippets/document-field/generated/cpf/cpf-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidCpf } from "@brazilian-utils/brazilian-utils";
import { CpfField } from "./cpf-field";

export function CpfForm() {
  const { control, handleSubmit } = useForm({ defaultValues: { cpf: "" } });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="cpf"
        control={control}
        rules={{ validate: (value) => isValidCpf(value) || "Enter a valid CPF" }}
        render={({ field, fieldState }) => (
          <>
            <CpfField {...field} />
            {fieldState.error && <p role="alert">{fieldState.error.message}</p>}
          </>
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}
