// docs/snippets/document-field/generated/cep/cep-form.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { isValidCep } from "@brazilian-utils/brazilian-utils";
import CepField from "./cep-field.vue";

const { defineField, errors, handleSubmit } = useForm({
  initialValues: { cep: "" },
  validationSchema: {
    cep: (value: string) => isValidCep(value) || "Enter a valid CEP",
  },
});

const [cep] = defineField("cep");

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <CepField v-model="cep" />
    <p v-if="errors.cep" role="alert">{{ errors.cep }}</p>
    <button type="submit">Submit</button>
  </form>
</template>

// docs/snippets/document-field/generated/cep/react/cep-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidCep } from "@brazilian-utils/brazilian-utils";
import { CepField } from "./cep-field";

export function CepForm() {
  const { control, handleSubmit } = useForm({
    defaultValues: { cep: "" },
    mode: "onTouched",
  });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="cep"
        control={control}
        rules={{
          required: "Enter a CEP",
          validate: (value) => isValidCep(value) || "Enter a valid CEP",
        }}
        render={({ field, fieldState }) => (
          <CepField {...field} errorMessage={fieldState.error?.message} />
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}
