// docs/snippets/document-field/generated/cnpj/cnpj-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidCnpj } from "@brazilian-utils/brazilian-utils";
import { CnpjField } from "./cnpj-field";

export function CnpjForm() {
  const { control, handleSubmit } = useForm({ defaultValues: { cnpj: "" } });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="cnpj"
        control={control}
        rules={{ validate: (value) => isValidCnpj(value, { version: 2 }) || "Enter a valid CNPJ" }}
        render={({ field, fieldState }) => (
          <>
            <CnpjField {...field} />
            {fieldState.error && <p role="alert">{fieldState.error.message}</p>}
          </>
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}

// docs/snippets/document-field/generated/cnpj/vue/cnpj-form.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { isValidCnpj } from "@brazilian-utils/brazilian-utils";
import CnpjField from "./cnpj-field.vue";

const { defineField, errors, handleSubmit } = useForm({
  initialValues: { cnpj: "" },
  validationSchema: {
    cnpj: (value: string) => isValidCnpj(value, { version: 2 }) || "Enter a valid CNPJ",
  },
});

// The attributes carry the blur handler, so the field is validated once it is left.
const [cnpj, cnpjAttrs] = defineField("cnpj", {
  validateOnModelUpdate: false,
});

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <CnpjField
      v-model="cnpj"
      v-bind="cnpjAttrs"
      :error-message="errors.cnpj"
    />
    <button type="submit">Submit</button>
  </form>
</template>
