// docs/snippets/document-field/_templates/react-field.tsx
import { useId, type ComponentProps } from "react";
@@imports@@

@@mask@@

type @@Name@@FieldProps = Omit<ComponentProps<"input">, "value" | "onChange"> & {
  value: string;
  onChange: (value: string) => void;
};

export function @@Name@@Field({ value, onChange, ...props }: @@Name@@FieldProps) {
  const id = useId();
  const messageId = `${id}-message`;
  const valid = @@validator@@;
  const complete = valid || value.length === @@length@@;

  return (
    <>
      <label htmlFor={id}>@@label@@</label>
      <input
        {...props}
        id={id}
        inputMode="@@inputMode@@"
        autoComplete="@@autocomplete@@"
        placeholder="@@placeholder@@"
        value={value}
        aria-invalid={complete && !valid}
        // The message describes the field, next to whatever the form has to say about it.
        aria-describedby={[props["aria-describedby"], messageId].filter(Boolean).join(" ")}
        onChange={(event) =>
          onChange(
            mask({
              input: event.currentTarget,
              inputType: (event.nativeEvent as InputEvent).inputType,
              format: @@format@@,
            }),
          )
        }
      />
      {/* A live region is announced when its text changes, so it stays on the page, empty. */}
      <output id={messageId} htmlFor={id}>
        {complete && (valid ? "✓ Valid @@label@@" : "✗ Invalid @@label@@")}
      </output>
    </>
  );
}

// docs/snippets/document-field/_templates/angular-field.ts
import { Component, Input, computed, forwardRef, signal } from "@angular/core";
import { type ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
@@imports@@

@@mask@@

/** One id per field on the page, to tie each label and message to their own field. */
let fields = 0;

@Component({
  selector: "app-@@kind@@-field",
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => @@Name@@Field),
      multi: true,
    },
  ],
  template: `
    <label [for]="id">@@label@@</label>
    <input
      [id]="id"
      inputmode="@@inputMode@@"
      autocomplete="@@autocomplete@@"
      placeholder="@@placeholder@@"
      [value]="value()"
      [disabled]="disabled()"
      [attr.aria-invalid]="complete() && !valid()"
      [attr.aria-describedby]="describedBy()"
      (input)="onInput($event)"
      (blur)="onTouched()"
    />
    <!-- A live region is announced when its text changes, so it stays on the page, empty. -->
    <output [id]="messageId" [htmlFor]="id">
      {{ complete() ? (valid() ? "✓ Valid @@label@@" : "✗ Invalid @@label@@") : "" }}
    </output>
  `,
})
export class @@Name@@Field implements ControlValueAccessor {
  /** What else describes this field, the form's own error message for example. */
  @Input("aria-describedby") describes?: string;

  protected readonly id = `@@kind@@-${(fields += 1)}`;
  protected readonly messageId = `${this.id}-message`;
  protected readonly value = signal("");
  protected readonly disabled = signal(false);
  protected readonly valid = computed(() => @@validatorSignal@@);
  protected readonly complete = computed(
    () => this.valid() || this.value().length === @@length@@,
  );

  // The message describes the field, next to whatever the form has to say about it.
  protected describedBy(): string {
    return [this.describes, this.messageId].filter(Boolean).join(" ");
  }

  protected onChange: (value: string) => void = () => {};
  protected onTouched: () => void = () => {};

  writeValue(value: string | null): void {
    this.value.set(value ? @@formatCall@@ : "");
  }

  registerOnChange(onChange: (value: string) => void): void {
    this.onChange = onChange;
  }

  registerOnTouched(onTouched: () => void): void {
    this.onTouched = onTouched;
  }

  setDisabledState(disabled: boolean): void {
    this.disabled.set(disabled);
  }

  protected onInput(event: Event) {
    const value = mask({
      input: event.target as HTMLInputElement,
      inputType: (event as InputEvent).inputType,
      format: @@format@@,
    });

    this.value.set(value);
    this.onChange(value);
  }
}
