// docs/snippets/document-field/_templates/react-field.tsx
import { useId, type ComponentProps } from "react";
@@imports@@

@@mask@@

type @@Name@@FieldProps = Omit<ComponentProps<"input">, "value" | "onChange"> & {
  value: string;
  onChange: (value: string) => void;
};

export function @@Name@@Field({ value, onChange, ...props }: @@Name@@FieldProps) {
  // The message is tied to the field, so a screen reader reads it with the field.
  const messageId = useId();
  const valid = @@validator@@;
  const complete = valid || value.length === @@length@@;

  return (
    <label>
      @@label@@
      <input
        {...props}
        inputMode="@@inputMode@@"
        autoComplete="@@autocomplete@@"
        placeholder="@@placeholder@@"
        value={value}
        aria-invalid={complete && !valid}
        aria-describedby={complete ? messageId : undefined}
        onChange={(event) =>
          onChange(
            mask({
              input: event.currentTarget,
              inputType: (event.nativeEvent as InputEvent).inputType,
              format: @@format@@,
            }),
          )
        }
      />
      {complete && (
        <output id={messageId}>{valid ? "✓ Valid @@label@@" : "✗ Invalid @@label@@"}</output>
      )}
    </label>
  );
}

// docs/snippets/document-field/_templates/vue-field.vue
<script setup lang="ts">
import { computed, useId } from "vue";
@@imports@@

@@maskLocal@@

const value = defineModel<string>({ default: "" });

// The message is tied to the field, so a screen reader reads it with the field.
const messageId = useId();

const valid = computed(() => @@validatorValue@@);
const complete = computed(() => valid.value || value.value.length === @@length@@);

function onInput(event: Event) {
  value.value = mask({
    input: event.target as HTMLInputElement,
    inputType: (event as InputEvent).inputType,
    format: @@format@@,
  });
}
</script>

<template>
  <label>
    @@label@@
    <input
      inputmode="@@inputMode@@"
      autocomplete="@@autocomplete@@"
      placeholder="@@placeholder@@"
      :value="value"
      :aria-invalid="complete && !valid"
      :aria-describedby="complete ? messageId : undefined"
      @input="onInput"
    />
    <output v-if="complete" :id="messageId">
      {{ valid ? "✓ Valid @@label@@" : "✗ Invalid @@label@@" }}
    </output>
  </label>
</template>
