// docs/snippets/document-field/_templates/vue-form.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
@@formImports@@
import @@Name@@Field from "./@@kind@@-field.vue";

const { defineField, errors, handleSubmit } = useForm({
  initialValues: { @@kind@@: "" },
  validationSchema: {
    @@kind@@: (value: string) => @@validator@@ || "Enter a valid @@label@@",
  },
});

const [@@kind@@] = defineField("@@kind@@");

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <@@Name@@Field v-model="@@kind@@" />
    <p v-if="errors.@@kind@@" role="alert">{{ errors.@@kind@@ }}</p>
    <button type="submit">Submit</button>
  </form>
</template>

// docs/snippets/document-field/_templates/react/form.tsx
import { Controller, useForm } from "react-hook-form";
@@formImports@@
import { @@Name@@Field } from "./@@kind@@-field";

export function @@Name@@Form() {
  const { control, handleSubmit } = useForm({
    defaultValues: { @@kind@@: "" },
    mode: "onTouched",
  });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="@@kind@@"
        control={control}
        rules={{
          required: "Enter a @@label@@",
          validate: (value) => @@validator@@ || "Enter a valid @@label@@",
        }}
        render={({ field, fieldState }) => (
          <@@Name@@Field {...field} errorMessage={fieldState.error?.message} />
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}
