// docs/snippets/document-field/generated/cpf/angular/cpf-form.ts
import { Component } from "@angular/core";
import {
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
  type ValidatorFn,
} from "@angular/forms";
import { isValidCpf } from "@brazilian-utils/brazilian-utils";
import { CpfField } from "./cpf-field";

export const cpfValidator: ValidatorFn = (control) =>
  !control.value || isValidCpf(control.value) ? null : { cpf: true };

@Component({
  selector: "app-cpf-form",
  imports: [ReactiveFormsModule, CpfField],
  template: `
    <form [formGroup]="form" (ngSubmit)="submit()">
      <app-cpf-field formControlName="cpf" [errorMessage]="errorMessage()" />
      <button type="submit">Submit</button>
    </form>
  `,
})
export class CpfForm {
  protected readonly form = new FormGroup({
    cpf: new FormControl("", {
      nonNullable: true,
      validators: [Validators.required, cpfValidator],
    }),
  });

  protected get control() {
    return this.form.controls.cpf;
  }

  protected errorMessage(): string | undefined {
    if (this.control.valid || this.control.untouched) return undefined;

    return this.control.hasError("required") ? "Enter a CPF" : "Enter a valid CPF";
  }

  protected submit() {
    if (this.form.invalid) return this.form.markAllAsTouched();

    console.log(this.form.getRawValue());
  }
}

// docs/snippets/document-field/generated/cpf/react/cpf-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidCpf } from "@brazilian-utils/brazilian-utils";
import { CpfField } from "./cpf-field";

export function CpfForm() {
  const { control, handleSubmit } = useForm({
    defaultValues: { cpf: "" },
    mode: "onTouched",
  });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="cpf"
        control={control}
        rules={{
          required: "Enter a CPF",
          validate: (value) => isValidCpf(value) || "Enter a valid CPF",
        }}
        render={({ field, fieldState }) => (
          <CpfField {...field} errorMessage={fieldState.error?.message} />
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}
