// docs/snippets/document-field/generated/phone/vue/phone-field.vue
<script setup lang="ts">
import { computed, useId } from "vue";
import { formatPhone, parsePhone } from "@brazilian-utils/brazilian-utils";
import { vMask } from "./mask";

// The attributes the form puts on this component belong on the input, not on the label.
defineOptions({ inheritAttrs: false });

/** What the form says is wrong with the value, if anything. */
const { errorMessage } = defineProps<{ errorMessage?: string }>();

/** The Phone without its mask, the way the form holds it. */
const value = defineModel<string>({ required: true });

const format = (value: string) => formatPhone(value, { mask: "nanp" });
const id = useId();
const errorId = `${id}-error`;
const masked = computed(() => formatPhone(value.value, { mask: "nanp" }));

function onInput(event: Event) {
  value.value = parsePhone((event.target as HTMLInputElement).value);
}
</script>

<template>
  <!-- Masks a Phone while it is typed. Validation belongs to the form. -->
  <label :for="id">Phone</label>
  <input
    v-bind="$attrs"
    v-mask="format"
    :id="id"
    inputmode="numeric"
    autocomplete="tel-national"
    placeholder="(00) 00000-0000"
    :value="masked"
    :aria-invalid="Boolean(errorMessage)"
    :aria-describedby="errorId"
    @input="onInput"
  />
  <!-- On the page from the start, and announced when it gets its text. -->
  <p :id="errorId" role="alert">{{ errorMessage }}</p>
</template>

// docs/snippets/document-field/generated/phone/react/phone-field.tsx
import { useId, type ComponentProps } from "react";
import { formatPhone, parsePhone } from "@brazilian-utils/brazilian-utils";
import { useMask } from "./use-mask";

type PhoneFieldProps = Omit<ComponentProps<"input">, "value" | "onChange" | "ref"> & {
  /** The Phone without its mask, the way the form holds it. */
  value: string;
  /** Called with the Phone without its mask. */
  onChange: (value: string) => void;
  /** What the form says is wrong with the value, if anything. */
  errorMessage?: string;
};

/** Masks a Phone while it is typed. Validation belongs to the form. */
export function PhoneField({ value, onChange, errorMessage, ...props }: PhoneFieldProps) {
  const id = useId();
  const errorId = `${id}-error`;
  const ref = useMask((value: string) => formatPhone(value, { mask: "nanp" }));

  return (
    <>
      <label htmlFor={id}>Phone</label>
      <input
        {...props}
        ref={ref}
        id={id}
        inputMode="numeric"
        autoComplete="tel-national"
        placeholder="(00) 00000-0000"
        value={formatPhone(value, { mask: "nanp" })}
        aria-invalid={Boolean(errorMessage)}
        aria-describedby={errorId}
        onChange={(event) => onChange(parsePhone(event.currentTarget.value))}
      />
      {/* On the page from the start, and announced when it gets its text. */}
      <p id={errorId} role="alert">
        {errorMessage}
      </p>
    </>
  );
}
