// docs/snippets/document-field/generated/phone/phone-form.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { isValidPhone } from "@brazilian-utils/brazilian-utils";
import PhoneField from "./phone-field.vue";

const { defineField, errors, handleSubmit } = useForm({
  initialValues: { phone: "" },
  validationSchema: {
    phone: (value: string) => isValidPhone(value) || "Enter a valid Phone",
  },
});

const [phone] = defineField("phone");

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <PhoneField v-model="phone" />
    <p v-if="errors.phone" role="alert">{{ errors.phone }}</p>
    <button type="submit">Submit</button>
  </form>
</template>

// docs/snippets/document-field/generated/phone/react/phone-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidPhone } from "@brazilian-utils/brazilian-utils";
import { PhoneField } from "./phone-field";

export function PhoneForm() {
  const { control, handleSubmit } = useForm({
    defaultValues: { phone: "" },
    mode: "onTouched",
  });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="phone"
        control={control}
        rules={{
          required: "Enter a Phone",
          validate: (value) => isValidPhone(value) || "Enter a valid Phone",
        }}
        render={({ field, fieldState }) => (
          <PhoneField {...field} errorMessage={fieldState.error?.message} />
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}
