// docs/snippets/document-field/document-form.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useForm } from "vee-validate";
import DocumentField, { DOCUMENTS, type DocumentKind } from "./document-field.vue";

const kind = ref<DocumentKind>("cpf");
const spec = computed(() => DOCUMENTS[kind.value]);

const { defineField, errors, handleSubmit, resetForm } = useForm({
  initialValues: { value: "" },
  validationSchema: {
    value: (value: string) =>
      spec.value.validator(value) || `Enter a valid ${spec.value.label}`,
  },
});

const [value] = defineField("value");

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <label>
      Document
      <select v-model="kind" @change="resetForm()">
        <option v-for="(item, value) in DOCUMENTS" :key="value" :value="value">
          {{ item.label }}
        </option>
      </select>
    </label>

    <DocumentField :kind="kind" v-model="value" />
    <p v-if="errors.value" role="alert">{{ errors.value }}</p>

    <button type="submit">Submit</button>
  </form>
</template>

// docs/snippets/document-field/document-form.tsx
import { useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { DOCUMENTS, DocumentField, type DocumentKind } from "./document-field";

export function DocumentForm() {
  const [kind, setKind] = useState<DocumentKind>("cpf");
  const { control, handleSubmit, reset } = useForm({ defaultValues: { value: "" } });
  const spec = DOCUMENTS[kind];

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <label>
        Document
        <select
          value={kind}
          onChange={(event) => {
            setKind(event.target.value as DocumentKind);
            reset({ value: "" });
          }}
        >
          {Object.entries(DOCUMENTS).map(([value, item]) => (
            <option key={value} value={value}>
              {item.label}
            </option>
          ))}
        </select>
      </label>

      <Controller
        name="value"
        control={control}
        rules={{
          validate: (value) => spec.validator(value) || `Enter a valid ${spec.label}`,
        }}
        render={({ field, fieldState }) => (
          <>
            <DocumentField kind={kind} {...field} />
            {fieldState.error && <p role="alert">{fieldState.error.message}</p>}
          </>
        )}
      />

      <button type="submit">Submit</button>
    </form>
  );
}
