// docs/snippets/document-field/generated/cep/react/cep-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidCep } from "@brazilian-utils/brazilian-utils";
import { CepField } from "./cep-field";

export function CepForm() {
  const { control, handleSubmit } = useForm({
    defaultValues: { cep: "" },
    mode: "onTouched",
  });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="cep"
        control={control}
        rules={{
          required: "Enter a CEP",
          validate: (value) => isValidCep(value) || "Enter a valid CEP",
        }}
        render={({ field, fieldState }) => (
          <CepField {...field} errorMessage={fieldState.error?.message} />
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}

// docs/snippets/document-field/generated/cep/angular/cep-form.ts
import { Component } from "@angular/core";
import {
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
  type ValidatorFn,
} from "@angular/forms";
import { isValidCep } from "@brazilian-utils/brazilian-utils";
import { CepField } from "./cep-field";

export const cepValidator: ValidatorFn = (control) =>
  !control.value || isValidCep(control.value) ? null : { cep: true };

@Component({
  selector: "app-cep-form",
  imports: [ReactiveFormsModule, CepField],
  template: `
    <form [formGroup]="form" (ngSubmit)="submit()">
      <app-cep-field formControlName="cep" [errorMessage]="errorMessage()" />
      <button type="submit">Submit</button>
    </form>
  `,
})
export class CepForm {
  protected readonly form = new FormGroup({
    cep: new FormControl("", {
      nonNullable: true,
      validators: [Validators.required, cepValidator],
    }),
  });

  protected get control() {
    return this.form.controls.cep;
  }

  protected errorMessage(): string | undefined {
    if (this.control.valid || this.control.untouched) return undefined;

    return this.control.hasError("required") ? "Enter a CEP" : "Enter a valid CEP";
  }

  protected submit() {
    if (this.form.invalid) return this.form.markAllAsTouched();

    console.log(this.form.getRawValue());
  }
}
