// docs/snippets/document-field/generated/cnpj/cnpj-form.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { isValidCnpj } from "@brazilian-utils/brazilian-utils";
import CnpjField from "./cnpj-field.vue";

const { defineField, errors, handleSubmit } = useForm({
  initialValues: { cnpj: "" },
  validationSchema: {
    cnpj: (value: string) => isValidCnpj(value, { version: 2 }) || "Enter a valid CNPJ",
  },
});

const [cnpj] = defineField("cnpj");

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <CnpjField v-model="cnpj" />
    <p v-if="errors.cnpj" role="alert">{{ errors.cnpj }}</p>
    <button type="submit">Submit</button>
  </form>
</template>

// docs/snippets/document-field/generated/cnpj/react/cnpj-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidCnpj } from "@brazilian-utils/brazilian-utils";
import { CnpjField } from "./cnpj-field";

export function CnpjForm() {
  const { control, handleSubmit } = useForm({
    defaultValues: { cnpj: "" },
    mode: "onTouched",
  });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="cnpj"
        control={control}
        rules={{
          required: "Enter a CNPJ",
          validate: (value) => isValidCnpj(value, { version: 2 }) || "Enter a valid CNPJ",
        }}
        render={({ field, fieldState }) => (
          <CnpjField {...field} errorMessage={fieldState.error?.message} />
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}
