// docs/snippets/document-field/generated/cep/cep-form.tsx
import { Controller, useForm } from "react-hook-form";
import { isValidCep } from "@brazilian-utils/brazilian-utils";
import { CepField } from "./cep-field";

export function CepForm() {
  const { control, handleSubmit } = useForm({ defaultValues: { cep: "" } });

  return (
    <form onSubmit={handleSubmit((values) => console.log(values))}>
      <Controller
        name="cep"
        control={control}
        rules={{ validate: (value) => isValidCep(value) || "Enter a valid CEP" }}
        render={({ field, fieldState }) => (
          <>
            <CepField {...field} />
            {fieldState.error && <p role="alert">{fieldState.error.message}</p>}
          </>
        )}
      />
      <button type="submit">Submit</button>
    </form>
  );
}

// docs/snippets/document-field/generated/cep/vue/cep-form.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { isValidCep } from "@brazilian-utils/brazilian-utils";
import CepField from "./cep-field.vue";

const { defineField, errors, handleSubmit } = useForm({
  initialValues: { cep: "" },
  validationSchema: {
    cep: (value: string) => isValidCep(value) || "Enter a valid CEP",
  },
});

// The attributes carry the blur handler, so the field is validated once it is left.
const [cep, cepAttrs] = defineField("cep", {
  validateOnModelUpdate: false,
});

const onSubmit = handleSubmit((values) => console.log(values));
</script>

<template>
  <form @submit="onSubmit">
    <CepField
      v-model="cep"
      v-bind="cepAttrs"
      :error-message="errors.cep"
    />
    <button type="submit">Submit</button>
  </form>
</template>
